on:
  workflow_call:
    inputs:
      actor_name:
        description: |
          Name of the entity performing the action.
          Repository modifications (created tags, CHANGELOG.md, etc) will be
          attributed to this entity.
        type: string
        required: true
      actor_token:
        description: |
          GITHUB_TOKEN or PAT authorized to make changes to the repository
        type: string
        required: true
      actor_email:
        description: Email address of the given actor (i.e., used in 'git config')
        type: string
        required: true

jobs:
  bump-version:
    if: github.ref_protected && !startsWith(github.event.head_commit.message, 'bump:')
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ inputs.actor_token }}"
      - name: Pull custom bump-version-action
        uses: actions/checkout@v3
        with:
          repository: kerrys-learning-lab/bump-version-action
          path: bump-version-action
          ref: refs/heads/main
          token: ${{ inputs.actor_token }}
      - name: Update version and changelog
        id: cz
        uses: ./bump-version-action
        with:
          github_actor: ${{ inputs.actor_name }}
          github_token: ${{ inputs.actor_token }}
          git_name: ${{ inputs.actor_name }}
          git_email: ${{ inputs.actor_email }}
      - name: Print Version
        run: echo "${{ steps.cz.outputs.version }}"
