on:
  workflow_call:
    inputs:
      repository_ref:
        description: "Git ref to use for check-repo-settings-action"
        default: refs/heads/main
        required: false
        type: string
    secrets:
      actor_token:
        description: |
          GITHUB_TOKEN or PAT authorized to make changes to the repository
        required: true

jobs:
  check-repo-settings:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Verify repository settings"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.actor_token }}"
      - name: Check/assert repository settings
        uses: kerrys-learning-lab/check-repo-settings-action@v1
        with:
          github_token: ${{ secrets.actor_token }}
