on:
  workflow_call:
    secrets:
      actor_token:
        description: |
          GITHUB_TOKEN or PAT authorized to make changes to the repository
        required: true

jobs:
  check-repo-settings:
    runs-on: ubuntu-latest
    name: "Verify repository settings"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.actor_token }}"
      - name: Check/assert repository settings
        uses: kerrys-learning-lab/check-repo-settings-action@support-check-repository-settings-action
        with:
          github_token: ${{ secrets.actor_token }}
