on:
  workflow_call:
    secrets:
      actor_name:
        description: |
          Name of the entity performing the action.
          Repository modifications (created tags, CHANGELOG.md, etc) will be
          attributed to this entity.
        required: true
      actor_token:
        description: |
          GITHUB_TOKEN or PAT authorized to make changes to the repository
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  scan-image:
    runs-on: ubuntu-22.04
    permissions:
      packages: read
      security-events: write

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.actor_name }}
          password: ${{ secrets.actor_token }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        env:
          TRIVY_USERNAME: ${{ secrets.actor_name }}
          TRIVY_PASSWORD: ${{ secrets.actor_token }}
        with:
          image-ref: ${{ steps.parse_image_tag.outputs.image_tag }}
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"
          ignore-unfixed: true
          timeout: 10m0s

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: ${{ startsWith( github.ref, 'refs/tags/v') || contains(github.event.head_commit.message, '[test ci]') }}
        with:
          sarif_file: "trivy-results.sarif"
          # NOTE: The 'specically-generated token doesn't work, but the default
          #       token does.  Needs further investigation.
          # token: ${{ secrets.actor_token }}
