name: Docker image workflow

on:
  push:
  workflow_call:
    secrets:
      actor_name:
        description: |
          Name of the entity performing the action.
          Repository modifications (created tags, CHANGELOG.md, etc) will be
          attributed to this entity.
        required: true
      actor_token:
        description: |
          GITHUB_TOKEN or PAT authorized to make changes to the repository
        required: true
      actor_email:
        description: Email address of the given actor (i.e., used in 'git config')
        required: true

jobs:
  build-and-push-image:
    uses: kerrys-learning-lab/.github/.github/workflows/.build-docker-image.yml@initial-development
    secrets:
      actor_name: ${{ secrets.KERRYS_LEARNING_LAB_ACTOR }}
      actor_token: ${{ secrets.KERRYS_LEARNING_LAB_TOKEN }}

  bump-version:
    uses: kerrys-learning-lab/.github/.github/workflows/.bump-version.yml@initial-development
    needs: build-and-push-image
    secrets:
      actor_name: ${{ secrets.KERRYS_LEARNING_LAB_ACTOR }}
      actor_token: ${{ secrets.KERRYS_LEARNING_LAB_TOKEN }}
      actor_email: ${{ secrets.KERRYS_LEARNING_LAB_EMAIL }}
