name: Docker image workflow

on:
  - push
  - workflow_call

jobs:
  build-and-push-image:
    uses: kerrys-learning-lab/.github/.github/workflows/.build-docker-image.yml@initial-development
    secrets:
      actor_name: ${{ secrets.KERRYS_LEARNING_LAB_ACTOR }}
      actor_token: ${{ secrets.KERRYS_LEARNING_LAB_TOKEN }}

  bump-version:
    uses: kerrys-learning-lab/.github/.github/workflows/.bump-version.yml@initial-development
    needs: build-and-push-image
    secrets:
      actor_name: ${{ secrets.KERRYS_LEARNING_LAB_ACTOR }}
      actor_token: ${{ secrets.KERRYS_LEARNING_LAB_TOKEN }}
      actor_email: ${{ secrets.KERRYS_LEARNING_LAB_EMAIL }}
