name: No-build workflow

on:
  workflow_call:
    inputs:
      dot_github_repository_ref:
        description: "Git ref to use for .github repository"
        default: refs/heads/main
        required: false
        type: string
      check_repo_settings_action_repository_ref:
        description: "Git ref to use for check-repo-settings-action"
        default: refs/heads/main
        required: false
        type: string
    secrets:
      actor_name:
        description: |
          Name of the entity performing the action.
          Repository modifications (created tags, CHANGELOG.md, etc) will be
          attributed to this entity.
        required: true
      actor_token:
        description: |
          GITHUB_TOKEN or PAT authorized to make changes to the repository
        required: true
      actor_email:
        description: Email address of the given actor (i.e., used in 'git config')
        required: true

jobs:
  show-inputs:
    runs-on: ubuntu-latest
    name: "Verify repository settings"
    steps:
      - name: Show input
        run: echo "${{ inputs.repository_ref }}"

  ref-check-repo-settings:
    uses: kerrys-learning-lab/.github/.github/workflows/.check-repo-settings.yml@${{ inputs.dot_github_repository_ref }}
    with:
      repository_ref: ${{ inputs.check_repo_settings_action_repository_ref }}
    secrets:
      actor_token: ${{ secrets.actor_token }}
  ref-bump-version:
    uses: kerrys-learning-lab/.github/.github/workflows/.bump-version.yml@${{ inputs.dot_github_repository_ref }}
    needs: ref-check-repo-settings
    secrets:
      actor_name: ${{ secrets.actor_name }}
      actor_token: ${{ secrets.actor_token }}
      actor_email: ${{ secrets.actor_email }}
