name: Build Python package and publish to PyPi

on:
  workflow_call:
    inputs:
      publish:
        description: >
          If true, publishes to the applicable (language-dependent)
          package repositories
        type: boolean
        default: true
        required: false
    secrets:
      actor_name:
        description: |
          Name of the entity performing the action.
          Repository modifications (created tags, CHANGELOG.md, etc) will be
          attributed to this entity.
        required: true
      actor_token:
        description: |
          GITHUB_TOKEN or PAT authorized to make changes to the repository
        required: true
      actor_email:
        description: Email address of the given actor (i.e., used in 'git config')
        required: true

jobs:
  ref-prerequisites:
    uses: ./.github/workflows/.prerequisites.yml

  ref-check-repo-settings:
    uses: kerrys-learning-lab/.github/.github/workflows/.check-repo-settings.yml@main
    secrets:
      actor_token: ${{ secrets.actor_token }}

  ref-python-package-pypi:
    uses: ./.github/workflows/.python-package-pypi.yml
    needs:
      - ref-prerequisites
      - ref-check-repo-settings
    with:
      publish: ${{ startsWith( github.ref, 'refs/tags/v') || contains(github.event.head_commit.message, '[test ci]') }}
    secrets:
      actor_token: ${{ secrets.KERRYS_LEARNING_LAB_TOKEN }}

  ref-bump-version:
    uses: kerrys-learning-lab/.github/.github/workflows/.bump-version.yml@main
    needs:
      - ref-prerequisites
      - ref-check-repo-settings
      - ref-python-package-pypi
    secrets:
      actor_name: ${{ secrets.actor_name }}
      actor_token: ${{ secrets.actor_token }}
      actor_email: ${{ secrets.actor_email }}
