name: ROS2 Library workflow

on:
  workflow_call:
    secrets:
      actor_name:
        description: |
          Name of the entity performing the action.
          Repository modifications (created tags, CHANGELOG.md, etc) will be
          attributed to this entity.
        required: true
      actor_token:
        description: |
          GITHUB_TOKEN or PAT authorized to make changes to the repository
        required: true
      actor_email:
        description: Email address of the given actor (i.e., used in 'git config')
        required: true

env:
  REGISTRY: ghcr.io
  LIBRARY_NAME: ${{ github.repository }}

jobs:
  build-and-publish-library:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/kerrys-learning-lab/devcontainer-ros2:latest
      credentials:
        username: ${{ secrets.actor_name }}
        password: ${{ secrets.actor_token }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern=v{{version}}
            type=sha,prefix=${{ github.ref_name }}--{{ date 'YYYY-MM-DD' }}--
            type=raw,value=latest,enable=${{ startsWith( github.ref, 'refs/tags/v') }}

      - name: Find ROS2 libraries
        shell: /bin/bash --noprofile --norc -eo pipefail {0}
        id: find_libraries
        run: |
          echo "::set-output name=ROS2_LIBRARIES::$(
            xmllint --xpath '//package/name/text()' $(find src -name package.xml)
          )"

      - name: Build the ROS2 libraries
        shell: /bin/bash --noprofile --norc -eo pipefail {0}
        run: |
          source /opt/ros/humble/setup.bash
          colcon build

      - name: Create library artifacts
        shell: /bin/bash --noprofile --norc -eo pipefail {0}
        run: |
          cd install
          for library in ${{ steps.find_libraries.output.ROS2_LIBRARIES }}; do
            tar czf ${library}.tar.gz ${library}
          done

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: install/*.tar.gz

  bump-version:
    uses: kerrys-learning-lab/.github/.github/workflows/.bump-version.yml@main
    needs: build-and-publish-library
    secrets:
      actor_name: ${{ secrets.actor_name }}
      actor_token: ${{ secrets.actor_token }}
      actor_email: ${{ secrets.actor_email }}
